apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: teleport-app-deployer
  namespace: nginx-app
subjects:
  - kind: Group
    name: teleport-app-deployers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: app-deployer
  apiGroup: rbac.authorization.k8s.io
